### ISSUE TITLE
문의글 기능 프론트엔트 작업

### ISSUE THREAD

**Issue by kinglim00** [DreamOfNemo/frontend#4]
## 💡 주요 기능
문의글 기능 프론트엔드 작업

## 💡 기능 상세 설명
![화면](https://github.com/DreamOfNemo/frontend/assets/70855011/bf2dca68-27bc-4aad-bd60-1685060b9d1f)

## 💡 예상 소요 시간
1주일

## 💡 Todo
- [x] 문의글 작성 기본틀 제작
- [x] 문의글 내용 전체 조회
- [x]  로컬 서버 연동 및 확인
- [x] 문의글 조회 UI 제작
- [x] 문의글 작성 UI 제작
- [x] 문의글 페이징 프론트 작업 필요

## 💡 비고
recoil이 다소 어렵게 느껴져서 우선 useState 쓰는 방법으로 구현하고 있습니다 :) 우선 프론트 작업을 끝낸 뒤, 추후 recoil로 수정해볼게요!
